import type { Metadata } from "next";
import "./globals.css";
import SupabaseProvider from "./supabase-provider";

export const metadata: Metadata = {
  title: "Twitter Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SupabaseProvider>{children}</SupabaseProvider>
        </body>
    </html>
  );
}
